lib/views/side_menu.dart

Linked to https://github.com/lenra-io/Lenra/issues/131

feat: Change doc link

---

pubspec.lock
pubspec.yaml

feat: Update dependencies

---

web/index.html

feat: Add LENRA_SERVER_URL in meta

---

lib/views/overview_page.dart
pubspec.lock
pubspec.yaml

Linked to https://github.com/lenra-io/client-common/issues/53

feat: Fix API requests

---

lib/main.dart

Linked to https://github.com/lenra-io/lenra_components/issues/114

fix: Textfield size

---

.github/workflows/semantic_release.yml

ci: Semantic Release Flutter Version Fix

---

lib/views/select_project_page.dart

Closes https://github.com/lenra-io/client-backoffice/issues/58

fix: New project button was removed

---

lib/views/backoffice_drawer.dart

fix: Backoffice drawer logo size

---

lib/views/create_project_form.dart
pubspec.lock
pubspec.yaml

Closes https://github.com/lenra-io/client-backoffice/issues/62

fix: App name already taken error

---

.gitignore
lib/navigation/backoffice_navigator.dart
lib/views/select_project_page.dart
pubspec.lock
pubspec.yaml

fix: Navigator GoRouter reorganized

---

lib/views/select_project_page.dart

Closes https://github.com/lenra-io/backoffice/issues/72

feat: Add scroll on select project page

---

lib/navigation/backoffice_navigator.dart
pubspec.lock
pubspec.yaml

Linked to https://github.com/lenra-io/client/issues/48

fix: Navigation back button

---

entrypoint.sh
lib/main.dart
pubspec.yaml
web/index.html

Must be merged with https://github.com/lenra-io/client-common/pull/74 and https://github.com/lenra-io/client/pull/53

feat: allow to load SentryDSN at runtime

---

lib/navigation/guard.dart

fix: Navigation to welcome

---

macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

feat: Update all deps

---

.github/workflows/semantic_release.yml
README.md

Closes https://github.com/lenra-io/backoffice/issues/71

docs: Adapt README and CI

---

pubspec.lock
pubspec.yaml

feat: Update client-common

---

lib/views/overview_page.dart

fix: deployment status & print

---

lib/views/overview_page.dart

Linked to https://github.com/lenra-io/server/issues/356

fix: Pending build autorefresh

---

lib/views/settings/git_integration_page.dart

Closes https://github.com/lenra-io/backoffice/issues/89

fix: Git Integration URL changed

---

lib/views/select_project_page.dart

Closes https://github.com/lenra-io/lenra_cli/issues/194

fix: Project selection status sticker

---

lib/views/oauth_page.dart

See https://github.com/xaynetwork/xayn_ai/pull/118

fix: Oauth page code asset

---

nginx.conf

It seems that images are not properly loaded on staging and production because of a missing entry in the Content Security Policy definition. I added the entry following this recommendation : https://stackoverflow.com/a/59485202
Test directly in staging

fix: Content Security Policy for blob

---

lib/views/backoffice_drawer.dart

Changed the link to which we redirect when clicking on "contact us". We go to lenra.io/contact.html instead of opening the mail app.

feat: Change contact redirection to website

---

lib/views/overview_page.dart

The timer on the Overview Page was being run very frequently (more than once per second) instead of one time each 5 seconds. This was due to a bug that is fixed in this PR.
I made sure that the Timer is only instantiated once and properly disposed.
I also changed the `select` to `read` on the Model calls because it was rebuilding the UI when it should not. I don't think that we will need to watch on these values so the `read` is enough.

fix: Timer is now properly executed each 5 seconds

---

.github/workflows/flutter.yml

Closes #110 
Remove PR-IS-WIP because it's broken

ci: Remove PR-IS-WIP because it's broken

---

lib/views/subscription_page.dart

fix: stripe redirect

---

lib/views/subscription_page.dart
web/subscription_redirect.html

Closes # 
See https://github.com/flutter/flutter/issues/57536#issuecomment-1386045229
This link explains how I handled the redirect on this PR.

fix: Subscription redirect

---

entrypoint.sh
lib/main.dart
pubspec.lock
pubspec.yaml

Closes https://github.com/lenra-io/kubernetes/issues/130
We can't set environment at runtime for client and backoffice.
This PR allow to set in the index.html file the metadata environment with a value at runtime instead of being stuck at compile time.

fix: add environment from runtime

---

pubspec.lock
pubspec.yaml

feat: Use main release on deps

---

lib/main.dart
lib/views/dev_validation_page.dart
lib/views/oauth_page.dart
pubspec.lock
pubspec.yaml

Linked to https://github.com/lenra-io/server/issues/399
This PR add an error handling when the API call on `/me` is not successful. It can happen that the current access token is not valid and this means that the `/me` API call returns an invalid_token error, which is caught here.

fix: oauth access token invalid

---

.vscode/settings.json
README.md
lib/views/backoffice_drawer.dart
lib/views/create_project_form.dart
lib/views/oauth_page.dart
pubspec.lock
pubspec.yaml

If there is no access token in local storage, the access token in OAuthModel should not act as an authentication method.

fix: OAuth disconnect
